#create namespace stackable
---
apiVersion: v1
kind: Namespace
metadata:
  name: stackable
---
apiVersion: s3.stackable.tech/v1alpha1
kind: S3Connection
metadata:
  name: minio
  namespace: stackable
spec:
  host: minio
  port: 9000
  accessStyle: Path
  credentials:
    secretClass: hive-s3-secret-class
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-s3-secret
  namespace: stackable
  labels:
    secrets.stackable.tech/class: hive-s3-secret-class
stringData:
  accessKey: hive
  secretKey: hivehive
---
apiVersion: secrets.stackable.tech/v1alpha1
kind: SecretClass
metadata:
  name: hive-s3-secret-class
  namespace: stackable
spec:
  backend:
    k8sSearch:
      searchNamespace:
        pod: {}
---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: hive-postgres-s3
  namespace: stackable
spec:
  image:
    productVersion: 3.1.3
  clusterConfig:
    database:
      connString: jdbc:postgresql://postgresql.default.svc.cluster.local:5432/hive
      credentialsSecret: hive-credentials
      dbType: postgres
    s3:
      reference: minio
  metastore:
    roleGroups:
      default:
        replicas: 1
---
apiVersion: v1
kind: Secret
metadata:
  name: hive-credentials
  namespace: stackable
type: Opaque
stringData:
  username: hive
  password: hive        
