apiVersion: v1
kind: Pod
metadata:
  name: caddy
  labels:
    app: caddy
spec:
  containers:
  - name: caddy
    image: caddy:2
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
        protocol: TCP
        name: http

---
apiVersion: v1
kind: Service
metadata:
  name: caddy
spec:
  selector:
    app: caddy
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
